config/routes.rb
Rails.application.routes.draw do
  root to: 'dashboard#index'

  get '/dashboard', to: 'dashboard#index'

  get '/wildlife_data', to: 'genres#wildlife_data', as: 'wildlife_data'
  get '/landscape_data', to: 'genres#landscape_data', as: 'landscape_data'
  get '/macro_data', to: 'genres#macro_data', as: 'macro_data'
  get '/astro_data', to: 'genres#astro_data', as: 'astro_data'

  get '/capture_time_data', to: 'images#capture_time_data', as: 'capture_time_data'
  get '/keyword_data', to: 'images#keyword_data', as: 'keyword_data'
  get '/ratings_data', to: 'images#ratings_data', as: 'ratings_data'

  get '/health_check_data', to: 'health_checks#index', as: 'health_check_data'

  get '/develop_settings_data', to: 'develop_settings#index', as: 'develop_settings_data'

  get '/collections_data', to: 'collections#index', as: 'collections_data'

  get '/equipment_form', to: 'equipment#index', as: 'equipment_form'
  post '/by_camera', to: 'equipment#by_camera', as: 'by_camera'
  post '/by_lens', to: 'equipment#by_lens', as: 'by_lens'
  post '/by_camera_and_lens', to: 'equipment#by_camera_and_lens', as: 'by_camera_and_lens'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/camera.rb
# frozen_string_literal: true

class Camera < ApplicationRecord
  self.table_name = 'AgInternedExifCameraModel'

  scope :for_model_name, ->(model_name) { where(value: model_name) }
  scope :canon_dslr, -> { where("value like ?", "%Canon EOS%") }
end

app/models/collection.rb
# frozen_string_literal: true

class Collection < ApplicationRecord
  self.table_name = 'AgLibraryCollection'

  scope :viewable, -> { where(systemOnly: 0) }
end

app/models/collection_image.rb
# frozen_string_literal: true

class CollectionImage < ApplicationRecord
  self.table_name = 'AgLibraryCollectionImage'
end

app/models/develop_setting.rb
# frozen_string_literal: true

class DevelopSetting < ApplicationRecord
  self.table_name = 'Adobe_imageDevelopSettings'

  UNCROPPED = 'uncropped'

  scope :cropped, -> { where.not(croppedWidth: UNCROPPED) }
  scope :developed, -> { where(hasDevelopAdjustmentsEx: 1.0) }

  def uncropped?
    croppedWidth == UNCROPPED
  end

  def cropped?
    !uncropped?
  end

  def crop_ratio
    return unless cropped?
    return if missing_size_information?

    fraction = (croppedWidth.to_d / croppedHeight.to_d).to_r.rationalize(0.05)

    "#{fraction.numerator} x #{fraction.denominator}"
  end

  def missing_size_information?
    # this appears to happen for video files
    croppedWidth.nil? && croppedHeight.nil? && fileHeight.nil? && fileWidth.nil?
  end

  def lens_profile_corrections?
    profileCorrections == 1
  end

  def chromatic_aberration_corrections?
    removeChromaticAberration == 1
  end
end

app/models/develop_settings.rb
# frozen_string_literal: true

class DevelopSettings < ApplicationRecord
  self.table_name = 'Adobe_imageDevelopSettings'
end

app/models/exif.rb
# frozen_string_literal: true

class Exif < ApplicationRecord
  self.table_name = 'AgHarvestedExifMetadata'

  scope :wildlife, -> { where('focalLength >= ?', 200.0) }
  scope :wide_angle_landscape, -> { where('focalLength <= ? AND isoSpeedRating = ?', 35.0, 100.0).by_camera(Camera.canon_dslr.pluck(:id_local)) }
  scope :macro, -> { by_lens(Lens.macro.pluck(:id_local)) }
  scope :astro, -> { where('aperture <= ? AND isoSpeedRating >= ?', 4.0, 3200.0) }
  scope :by_camera, ->(camera_id) { where(cameraModelRef: camera_id) }
  scope :by_lens, ->(lens_id) { where(lensRef: lens_id) }
  scope :by_year, ->(year) { where(dateYear: year) }

  def shutter_speed_value
    return unless shutterSpeed.present?

    if shutterSpeed.negative?
      (2**-shutterSpeed).round
    else
      speed = (2**shutterSpeed).round
      format_speed(speed)
    end
  end

  def month_and_year
    return unless dateMonth.present? && dateYear.present?

    "#{Date::MONTHNAMES[dateMonth]} #{dateYear.to_i}"
  end

  private

  def format_speed(speed)
    if speed == 1
      1
    else
      "1/#{speed}".to_r
    end
  end
end

app/models/image.rb
# frozen_string_literal: true

class Image < ApplicationRecord
  self.table_name = 'Adobe_images'

  # Rating scopes
  scope :unrated, -> { where(rating: nil) }
  scope :rated, -> { where.not(rating: nil) }
  scope :with_star_rating, ->(rating) { where(rating: rating) }

  # Capture time scopes
  scope :for_month, ->(month) { where('captureTime LIKE ?', "%-#{month}-%") }
  scope :for_year, ->(year) { where('captureTime LIKE ?', "#{year}-%") }

  def capture_hour
    if captureTime.is_a?(DateTime) || captureTime.is_a?(Time)
      captureTime.hour
    else
      Time.parse(captureTime).hour
    end
  end
end

app/models/image_file.rb
# frozen_string_literal: true

class ImageFile < ApplicationRecord
  self.table_name = 'AgLibraryFile'
end

app/models/keyword.rb
# frozen_string_literal: true

class Keyword < ApplicationRecord
  self.table_name = 'AgLibraryKeyword'
end

app/models/keyword_image.rb
# frozen_string_literal: true

class KeywordImage < ApplicationRecord
  self.table_name = 'AgLibraryKeywordImage'

  scope :by_image, ->(image_id) { where(image: image_id) }
end

app/models/keyword_popularity.rb
# frozen_string_literal: true

class KeywordPopularity < ApplicationRecord
  self.table_name = 'AgLibraryKeywordPopularity'
end

app/models/keyword_synonym.rb
# frozen_string_literal: true

class KeywordSynonym < ApplicationRecord
  self.table_name = 'AgLibraryKeywordSynonym'
end

app/models/lens.rb
# frozen_string_literal: true

class Lens < ApplicationRecord
  self.table_name = 'AgInternedExifLens'

  scope :for_model_name, ->(model_name) { where(value: model_name) }
  scope :macro, -> { where("value like ?", "%Macro%") }
end

app/models/metadata.rb
# frozen_string_literal: true

class Metadata < ApplicationRecord
  self.table_name = 'Adobe_AdditionalMetadata'
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/camera_helper.rb
# frozen_string_literal: true

module CameraHelper
  def cameras_for_select
    camera_names = Camera.pluck(:value).uniq.sort

    camera_names.map do |name|
      [name, name]
    end
  end
end

app/helpers/collection_helper.rb
# frozen_string_literal: true

module CollectionHelper
  def collection_overview_text(collection_count)
    "There #{verb(collection_count)} #{pluralize(collection_count, 'collection')}"
  end

  private

  def verb(collection_count)
    collection_count == 1 ? 'is' : 'are'
  end
end

app/helpers/exif_helper.rb
# frozen_string_literal: true

module ExifHelper
  def years_for_select
    years = Exif.pluck(:dateYear).compact.uniq.sort.reverse.map(&:round)

    years.map do |year|
      [year, year]
    end
  end
end

app/helpers/lens_helper.rb
# frozen_string_literal: true

module LensHelper
  def lenses_for_select
    Lens.pluck(:value).uniq.sort.map do |lens_name|
      [lens_name, lens_name]
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lightroom Classic Analysis</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1>Lightroom Classic Analysis</h1>

    <%= render partial: 'shared/navigation' %>

    <%= yield %>
  </body>
</html>

app/views/shared/_data_list.html.erb
<dt><%= heading %>:</dt>
<dd>
  <ul>
    <% data.each do |item| %>
      <li><%= item[:value] %> (<%= item[:percentage] %>%)</li>
    <% end %>
  </ul>
</dd>

app/views/shared/_data_list_with_prefix_and_suffix.html.erb
<dt><%= heading %>:</dt>
<dd>
  <ul>
    <% data.each do |item| %>
      <li><%= item_prefix %><%= item[:value] %><%= item_suffix %> (<%= item[:percentage] %>%)</li>
    <% end %>
  </ul>
</dd>

app/views/shared/_navigation.html.erb
<div class="menu">
  <ul>
    <li><%= link_to 'Most Popular', dashboard_path %></li>
    <li><%= link_to 'Health Check', health_check_data_path %></li>
    <li><%= link_to 'Collection Data', collections_data_path %></li>
    <li><%= link_to 'Capture Time Data', capture_time_data_path %></li>
    <li><%= link_to 'Wildlife Data', wildlife_data_path %></li>
    <li><%= link_to 'Landscape Data', landscape_data_path %></li>
    <li><%= link_to 'Macro Data', macro_data_path %></li>
    <li><%= link_to 'Astro Data', astro_data_path %></li>
    <li><%= link_to 'Keywords', keyword_data_path %></li>
    <li><%= link_to 'Ratings', ratings_data_path %></li>
    <li><%= link_to 'Develop Settings', develop_settings_data_path %></li>
    <li><%= link_to 'By Camera or Lens', equipment_form_path %></li>
  </ul>
</div>

app/views/shared/_rating_row.html.erb
<tr>
  <td><%= data[:rating] %></td>
  <td><%= pluralize(data[:count], 'image') %> (<%= data[:percentage] %>%)</td>
</tr>

app/views/shared/_ratings_by_equipment.html.erb
<dt>Ratings:</dt>
<dd>
  <table>
    <tr>
      <th>Rating</th>
      <th>Number of images</th>
    </tr>

    <% data.each do |_rating_key, rating_data| %>
      <%= render partial: 'shared/rating_row', locals: { data: rating_data } %>
    <% end %>
  </table>
</dd>